# Authentication Tests
print_section "Authentication Tests"
check_result "Is email and password required for registration?"
check_result "Does the system detect wrong email/password?"
check_result "Does the system detect duplicate email/username?"
check_result "Is registration working properly?"
check_result "Can you login with created user?"
check_result "Does empty login show warning?"
check_result "Are sessions working properly?"
check_result "Do different browsers maintain separate sessions?"
check_result "Is single session per user enforced?"
check_result "Are posts/comments visible across sessions?"

# SQLite Tests
print_section "SQLite Tests"
check_result "Does code contain CREATE queries?"
check_result "Does code contain INSERT queries?"
check_result "Does code contain SELECT queries?"
check_result "Are registered users stored in database?"
check_result "Are posts stored in database?"
check_result "Are comments stored in database?"

# Docker Tests
print_section "Docker Tests"
check_result "Does project have Dockerfiles?"
check_result "Do images build successfully?"
check_result "Do containers run properly?"
check_result "Are there no unused Docker objects?"

# Functional Tests
print_section "Functional Tests"
check_result "Are non-registered users prevented from posting?"
check_result "Are non-registered users prevented from commenting?"
check_result "Are non-registered users prevented from liking?"
check_result "Are non-registered users prevented from disliking?"
check_result "Can registered users create comments?"
check_result "Are empty comments prevented?"
check_result "Can registered users create posts?"
check_result "Are empty posts prevented?"
check_result "Can users select multiple categories for posts?"
check_result "Can users select single category for posts?"
check_result "Does like/dislike work for posts?"
check_result "Does like/dislike work for comments?"
check_result "Do like/dislike counts persist after refresh?"
check_result "Is simultaneous like/dislike prevented?"
check_result "Can users view their created posts?"
check_result "Can users view their liked posts?"
check_result "Are like/dislike counts visible to all users?"
check_result "Does category filtering work?"

# Technical Tests
print_section "Technical Tests"
check_result "Does server handle requests without crashing?"
check_result "Are correct HTTP methods used?"
check_result "Are all pages working (no 404)?"
check_result "Is HTTP 400 handled properly?"
check_result "Is HTTP 500 handled properly?"
check_result "Are only allowed packages used?"

# Bonus Features
print_section "Bonus Features"
check_result "Is there a build script for Docker?"
check_result "Are passwords encrypted in database?"
check_result "Does code follow good practices?"
check_result "Are there test files?"
check_result "Does the project run efficiently?"
